mod-name: NearFutureSpacecraft
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - NearFutureSpacecraft
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.3
    location: s3
  B9PartSwitch:
    version: 2.13.0
    location: s3
  NearFutureProps:
    tag: 0.6.2
    location: github
    repository: ChrisAdderley/NearFutureProps
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 708  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 220677  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
